name: fact
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _pytorch_select=1.1.0
  - blas=1.0
  - ca-certificates=2019.11.27
  - certifi=2019.11.28
  - cffi=1.13.2
  - cudatoolkit=10.0.130
  - cudnn=7.6.5
  - icc_rt=2019.0.0
  - intel-openmp=2019.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ninja=1.9.0
  - numpy=1.17.4
  - numpy-base=1.17.4
  - openssl=1.1.1d
  - pip=19.3.1
  - pycparser=2.19
  - python=3.7.6
  - pytorch=1.3.1
  - setuptools=44.0.0
  - six=1.13.0
  - sqlite=3.30.1
  - tk=8.6.8
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wheel=0.33.6
  - wincertstore=0.2
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - boto==2.49.0
    - boto3==1.11.1
    - botocore==1.14.1
    - chardet==3.0.4
    - docutils==0.15.2
    - gensim==3.8.1
    - idna==2.8
    - jmespath==0.9.4
    - python-dateutil==2.8.1
    - requests==2.22.0
    - s3transfer==0.3.0
    - scipy==1.4.1
    - smart-open==1.9.0
    - urllib3==1.25.7

